# Generated by Django 3.0.2 on 2024-06-20 13:14

from django.db import migrations, models
import django.utils.crypto


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(default=django.utils.crypto.get_random_string, max_length=23)),
                ('product_image', models.ImageField(upload_to='product_image/')),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], max_length=100)),
                ('product_status', models.CharField(choices=[('Order Confirmed', 'Order Confirmed'), ('Picked Up By Courier', 'Picked Up By Courier'), ('On The Way', 'On The Way'), ('Ready For Pickup', 'Ready For Pickup')], default='Order Confirmed', max_length=100)),
                ('product_name', models.CharField(max_length=250)),
                ('shipment_origin', models.CharField(max_length=250)),
                ('shipment_destination', models.CharField(max_length=250)),
                ('transportation_type', models.CharField(max_length=250)),
                ('shipment_product_details', models.CharField(max_length=250)),
                ('shipment_weight', models.CharField(max_length=250)),
                ('pickup_date', models.DateTimeField()),
                ('scheduled_delivery_date', models.DateTimeField()),
                ('shippers_full_name', models.CharField(max_length=250)),
                ('shippers_phone_number', models.CharField(max_length=15)),
                ('shippers_address', models.CharField(max_length=250)),
                ('receivers_full_name', models.CharField(max_length=250)),
                ('receivers_phone_number', models.CharField(max_length=15)),
                ('receivers_address', models.CharField(max_length=400)),
                ('last_location', models.CharField(max_length=400)),
                ('history_status', models.CharField(max_length=200)),
                ('remarks', models.CharField(max_length=400)),
                ('history_date', models.DateTimeField()),
                ('last_location2', models.CharField(blank=True, max_length=400)),
                ('history_status2', models.CharField(blank=True, max_length=200)),
                ('remarks2', models.CharField(blank=True, max_length=400)),
                ('history_date2', models.DateTimeField(blank=True, null=True)),
                ('last_location3', models.CharField(blank=True, max_length=400)),
                ('history_status3', models.CharField(blank=True, max_length=200)),
                ('remarks3', models.CharField(blank=True, max_length=400)),
                ('history_date3', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='YourMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
    ]
